#!/bin/bash

cd files
upper_array=(A B C D E F G H I J K L M N O P Q R S T U V W X Y Z)
lower_array=(a b c d e f g h i j k l m n o p q r s t u v w x y z)

for ((i=0; i<26; i++))
do mv ${upper_array[i]}* ${lower_array[i]}* /home/workspace/SWE_2021_41_2023_2_week_4-main/${lower_array[i]}
done
